 services:
  db:
    image: postgres:15
    container_name: inventory_db
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: inventory_app
    depends_on:
      - db
    stdin_open: true
    tty: true